#!/usr/bin/env ruby

require 'yaml'

cnf = YAML.load_file("config.yml")

puts cnf

docker = ""
port = ""
cnf.each do |k, v|
  docker += "docker run -p #{v.each do |ports| port += "#{ports} " end } #{v["image"]}\n "
end

puts docker 
