#db:
  #image: postgres 
  #mode:
    #- "d" 

app:
  image: owndjango
  mode: 
    - "t"
  ports:
    - "8000:8000"
  command: "python helloworld/manage.py runserver 0.0.0.0:8000"
  volumes:
    - "$PWD:/code"
  #links:
    #- "db:postgres"
